import React from 'react';
import Head from 'next/head'
import Navbar from '../componenet/Navbar/Navbar';
import Footer from '../componenet/Footer/Footer';


const layout = ({ children }) => {
    return (
        <div>
            <Head>
                <title>Noxe</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="../images/favicon.png" />
                <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" Crossorigin="anonymous"/>
                <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" Crossorigin="anonymous" />
                <script async src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" /> 
            </Head>
                <Navbar />
                {children }
               <Footer/>
        </div>
    );
};

export default layout;